### ISSUE TITLE
Botão de troca do tema

### ISSUE THREAD

**Issue by marcoantoniossilva** [flaviofilipe/bsi-ifba-web#10]
Não fica claro para o usuário a função do botão de troca de tema até acioná-lo. Talvez um ícone ajudaria.

**Comment by flaviofilipe** [comment]
Acho que poderíamos dar um destaque nele mesmo. Talvez fazer o contraste na bolinha de dentro fique legal.
@filipecancio O que acha?

**Comment by filipecancio** [comment]
Sim, eu lembro que eu pensei em fazer dois ícones na borda pra simbolizar. Mas fiquei com preguiça. O esquema de cores não ajuda tbm eu não tinha montado uma paleta de cores até então.
